<script setup>
import { onBeforeUnmount, ref, watch } from 'vue'
import axios from 'axios'
import { Download, FileText, X } from 'lucide-vue-next'
import Spinner from '@/Components/UI/Spinner.vue'
import { formatCurrency } from '@/Utils/helpers'
const props = defineProps({ payroll: { type: Object, default: null } })
const emit = defineEmits(['close'])
const items = ref([]); const loading = ref(false); const error = ref(''); let requestId = 0
const formatIndonesianDate = (value) => { if (!value) return '-'; const [year, month, day] = String(value).slice(0, 10).split('-'); return year && month && day ? `${day}/${month}/${year}` : value }
const load = async () => { if (!props.payroll?.id) return; const id = ++requestId; loading.value = true; error.value = ''; try { const response = await axios.get(route('api.hr.payrolls.items.index', { payroll: props.payroll.id })); if (id === requestId) items.value = response.data?.data?.data ?? [] } catch (e) { if (id === requestId) error.value = e.response?.data?.message || 'Rincian payroll gagal dimuat.' } finally { if (id === requestId) loading.value = false } }
watch(() => props.payroll?.id, load, { immediate: true }); onBeforeUnmount(() => { requestId += 1 })
</script>
<template><Teleport to="body"><div class="fixed inset-0 z-50 bg-slate-950/45" @click="emit('close')"></div><aside class="fixed inset-y-0 right-0 z-50 flex w-full max-w-2xl flex-col border-l border-slate-200 bg-white shadow-2xl dark:border-[#29476b] dark:bg-[#102542]"><header class="flex items-start justify-between border-b border-slate-100 p-5 dark:border-[#29476b]"><div class="flex items-center gap-3"><span class="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><FileText :size="20" /></span><div><p class="text-xs font-semibold uppercase tracking-wide text-emerald-600">Rincian Payroll</p><h2 class="text-lg font-semibold text-slate-950 dark:text-white">Periode {{ formatIndonesianDate(payroll?.period) }}</h2></div></div><button type="button" class="rounded-lg p-2 text-slate-400 hover:bg-slate-100" @click="emit('close')"><X :size="20" /></button></header><div class="flex-1 overflow-y-auto p-5"><div v-if="loading" class="flex min-h-56 items-center justify-center"><Spinner label="Memuat rincian slip gaji..." /></div><div v-else-if="error" class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ error }}</div><div v-else class="space-y-3"><div v-for="item in items" :key="item.id" class="rounded-xl border border-slate-200 p-4 dark:border-[#29476b]"><div class="flex items-center justify-between"><div><p class="font-semibold text-slate-900 dark:text-white">{{ item.employee?.name }}</p><p class="text-xs text-slate-500">{{ item.employee?.nik }}</p></div><a :href="route('api.hr.payroll-items.print', { item: item.id })" target="_blank" class="inline-flex items-center gap-1 text-sm font-semibold text-emerald-700"><Download :size="15" />Slip PDF</a></div><div class="mt-3 grid grid-cols-2 gap-2 text-sm"><span>Gaji Pokok <strong class="float-right">{{ formatCurrency(item.basic_salary) }}</strong></span><span>Tunjangan <strong class="float-right">{{ formatCurrency(item.allowance) }}</strong></span><span>Komisi <strong class="float-right">{{ formatCurrency(item.commission_amount) }}</strong></span><span>Lembur <strong class="float-right">{{ formatCurrency(item.overtime_amount) }}</strong></span><span>Potongan <strong class="float-right">{{ formatCurrency(item.deduction) }}</strong></span><span class="font-bold text-emerald-700">THP <strong class="float-right">{{ formatCurrency(item.net_salary) }}</strong></span></div></div></div></div></aside></Teleport></template>
